---
apiVersion: v1
kind: Service
metadata:
  name: front
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: clusterl
      port: 8080
  selector:
    app: clusterl
---
apiVersion: v1
kind: Service
metadata:
  name: clusterl
spec:
  clusterIP: None
  ports:
    - name: epmd
      port: 4369
  selector:
    app: clusterl
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clusterl
spec:
  replicas: 2
  serviceName: clusterl
  selector:
    matchLabels:
      app: clusterl
  template:
    metadata:
      labels:
        app: clusterl
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - clusterl
              topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        - name: docker
      containers:
        - name: clusterl
          imagePullPolicy: Always
          tty: true
          stdin: true
          image: docker.pkg.github.com/pedro-gutierrez/clusterl/clusterl:latest
          ports:
            - name: clusterl
              containerPort: 8080
              protocol: TCP
            - name: epmd
              containerPort: 4369
              protocol: TCP
          envFrom:
            - secretRef:
                name: secrets
          env:
            - name: DEPLOYMENT_VERSION
              value: "{{VERSION}}"
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
