name: Deploy
on:
  push: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deploy
        uses: pedro-gutierrez/deploy-action@v21
        with:
          docker_tag: latest
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          secrets_name: "clusterl"
          secrets: ${{ secrets.SECRETS }}
          scale: "statefulset:clusterl:2"
      - name: If errors, notify
        if: failure()
        uses: pedro-gutierrez/slack-action@v6
        with:
          slack_url: ${{ secrets.SLACK_URL }}
          status: failed
