name: Deploy
on:
  push: {}
  schedule:
    - cron: "0 2 * * *"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deploy
        uses: pedro-gutierrez/deploy-action@v17
        with:
          docker_tag: latest
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          secrets_name: "clusterl"
          secrets: ${{ secrets.SECRETS }}
      - name: Setup Erlang
        uses: gleam-lang/setup-erlang@v1.1.2
        with:
          otp-version: 22.1
      - name: Run integration tests
        run: rebar3 eunit
