name: Test 
on:
  push: {}
  schedule:
    - cron: "15 * * * *"
    - cron: "30 * * * *"
    - cron: "45 * * * *"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Erlang
        uses: gleam-lang/setup-erlang@v1.1.2
        with:
          otp-version: 22.1
      - name: Compile
        run: rebar3 compile
      - name: Test
        run: rebar3 eunit
      - name: If errors, notify
        if: failure()
        uses: pedro-gutierrez/slack-action@v6
        with:
          slack_url: ${{ secrets.SLACK_URL }}
          status: failed
